### ISSUE TITLE
Boolean searches don't work as expected

### ISSUE THREAD

**Issue by gjost** [densho/ddr-public#100]
Boolean searches do not return queries as expected (e.g., searches for firstname, lastname)

**Comment by GeoffFroh** [comment]
Need to add more information about what kinds of searches are not returning what we expect -- i.e., sample query strings and results

**Comment by sarabeckman** [comment]
The issue with search is when using more than one search term. 

For example, the search term  Native American brings back 4,203 results from the DDR. However, only about 15 of those results have anything to do with Native Americans. The rest of the results only have either American or Native. For example, after the first ~15 results, the results suddenly all become about Japanese Americans since it has American in the title or the description. 

Another example - "Yasui Family Collection" brings back 5,249 results. It does bring up the correct result first but it also brings up every other "family collection". 

This same problem of getting too many unrelated results is also an issue with any names. "Frank Sumida" bring back 1, 312 results but only the Visual History results match then you start getting unrelated Franks and some unrelated Sumidas.

**Comment by sarabeckman** [comment]
In a bit of a different result "Manzanar mess hall" brings back 948 results. The first result is a photograph of a mess hall at Manzanar. However, the results then are mixed. The results that have all three search terms are not all at the top. The records with Manzanar, mess, and hall are scattered throughout the first page of results as well as the second.

**Comment by sarabeckman** [comment]
The third case of search gone wrong is largely for the office user. Searching by collection id just doesn't work. For example, searching ddr-densho-160-72 brings back no good results

**Comment by GeoffFroh** [comment]
> The third case of search gone wrong is largely for the office user. Searching by collection id just doesn't work. For example, searching ddr-densho-160-72 brings back no good results

Behavior related to: https://github.com/densho/ddr-public/issues/103

**Comment by gjost** [comment]
Spent some time with Elasticsearch Reference [2.4].  We're currently running "match" queries on the fulltext search field, which I think we should be using "query_string" or "simple_query_string".
- https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-query-string-query.html
- https://www.elastic.co/guide/en/elasticsearch/reference/2.4/query-dsl-simple-query-string-query.html

**Comment by GeoffFroh** [comment]
The fix on stage looks good. We should commit that change and close this issue.

**Comment by gjost** [comment]
Fixed in commit ab39d162ad, merged into `develop`.
