### ISSUE TITLE
Numbered lists not displaying in order

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-public#133]
All lists based on collection numbers are not displaying in order on ddrstage. This behavior shows up on the[ collections page](https://ddrstage.densho.org/collections/), [objects page](https://ddrstage.densho.org/ddr-densho-203/objects/), and [file page](https://ddrstage.densho.org/ddr-densho-97-223/files/).

**Comment by gjost** [comment]
Mostly fixed in commit `1ccc791`.  Latest code pulled to ddrstage.

There is still an error on the [narrators browse page](https://ddrstage.densho.org/narrators/).

**Comment by gjost** [comment]
FYI the narrators issue has been fixed in commit `ef8dab6` which has been merged into the `develop` branch of `ddr-defs`.

The fix involved manually deleting the `ddrnarrators` index from the Elasticsearch cluster using `curl` - for some reason the `DDR` tools based on `elasticsearch_dsl` did not remove the index.
