### ISSUE TITLE
ui: Add site outage message for 12/11/2019

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#140]
Add a site outage message notice for the 12/11/2019 server maintenance.

**Comment by gjost** [comment]
Fixed in ddr-public commit `3193921` for package `ddrpublic-master_4.0.1~deb9`.

To set a sitewide message, edit `[public] site_msg_text` (HTML may be included) in [ansible-colo/templates/ddrpublic/ddrpublic-local.cfg.j2](https://github.com/densho/ansible-colo/blob/master/templates/ddrpublic/ddrpublic-local.cfg.j2) and execute the `ddrpublic.yml` playbook.  

To remove the message, edit `[piublic] site_msg_text` to remove text and execute the playbook again.
