### ISSUE TITLE
Files not sorting properly in entity detail or file list pages

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#56]
Files are sorted by sort order attribute. Currently, that value is treated as a string, rather than an integer on entity detail and file list pages.

**Comment by gjost** [comment]
Check if sort is an int in current ES documents.

If it's NOT an int,
[ddr-cmdln,ddr-defs] Make sure that sort is always converted to int when loading from JSON.
[ddr-defs] Make sure sort is an int in Elasticsearch mappings.
[ddr-cmdln] Test ddr-index to make sure sort is maintained as int in ES.

**Comment by GeoffFroh** [comment]
See, for example:

http://ddr.densho.org/ddr/densho/305/1/

**Comment by gjost** [comment]
Comparing an older collection [1] and a newer collection [2], `sort` is sometimes a string and sometimes an integer.

[1] http://ddr.densho.org/api/0.1/ddr/densho/266/9/children/
[2] http://ddr.densho.org/api/0.1/ddr/densho/305/1/children/

**Comment by gjost** [comment]
It looks like `sort` is currently mapped as a string:
```
ansible@lil:~$ wget http://127.0.0.1:9100/ddrpublic-production/file/_mapping
{"ddrpublic-production":{"mappings":{"file":{"date_detection":false,"properties":{"access_rel":{"type":"string"},"app_commit":{"type":"string"},"app_release":{"type":"string"},"application":{"type":"string"},"basename_orig":{"type":"string"},"cid":{"type":"long"},"commit":{"type":"string"},"digitize_person":{"type":"string"},"eid":{"type":"long"},"entity_id":{"type":"string"},"git":{"type":"string"},"git_version":{"type":"string"},"id":{"type":"string"},"label":{"type":"string"},"md5":{"type":"string"},"models_commit":{"type":"string"},"org":{"type":"string"},"parent_id":{"type":"string"},"path_rel":{"type":"string"},"public":{"type":"string"},"release":{"type":"string"},"repo":{"type":"string"},"rights":{"type":"string"},"role":{"type":"string"},"sha1":{"type":"string"},"sha256":{"type":"string"},"size":{"type":"long"},"sort":{"type":"string"},"tech_notes":{"type":"string"},"thumb":{"type":"long"},"title":{"type":"string"},"xmp":{"type":"string"}}}}}}
```

The Python API we're using for ES will let you specify a list of fields to sort on; you can further specify ascending or descending for each field.  The API does not include options for treating fields as either string or numeric.

https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html?highlight=sort#sorting

The Elasticsearch documentation has more detail and there are more options, but no options for treating integers inside string fields as if they were integers.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html

I think we're going to have to update the mappings and re-index everything in order to see changes.  The current `develop` branch of `ddr-index` produces a mapping that specifies `sort` as an integer.
